
var Module = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});g.oa||(g.oa=0);g.oa++;g.ENVIRONMENT_IS_PTHREAD||function(){function a(){g.FS_createPath("/","model",!0,!0);var b=g.___emscripten_embedded_file_data>>2;do{var c=k[b++],d=k[b++],e=k[b++];c=t(c);g.FS_createDataFile(c,null,w.subarray(e,e+d),!0,!0,!0)}while(k[b])}g.calledRun?a():(g.preRun||(g.preRun=[]),g.preRun.push(a))}({files:[]});
var ca=Object.assign({},g),da="./this.program",ea="object"==typeof window,z="function"==typeof importScripts,A="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,C="",D,E,fa,fs,ha,ia;
if(A)C=z?require("path").dirname(C)+"/":__dirname+"/",ia=()=>{ha||(fs=require("fs"),ha=require("path"))},D=function(a,b){ia();a=ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},fa=a=>{a=D(a,!0);a.buffer||(a=new Uint8Array(a));return a},E=(a,b,c)=>{ia();a=ha.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",
function(a){throw a;}),g.inspect=function(){return"[Emscripten Module object]"};else if(ea||z)z?C=self.location.href:"undefined"!=typeof document&&document.currentScript&&(C=document.currentScript.src),_scriptDir&&(C=_scriptDir),0!==C.indexOf("blob:")?C=C.substr(0,C.replace(/[?#].*/,"").lastIndexOf("/")+1):C="",D=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},z&&(fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
E=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ja=g.print||console.log.bind(console),G=g.printErr||console.warn.bind(console);Object.assign(g,ca);ca=null;g.thisProgram&&(da=g.thisProgram);var ka;g.wasmBinary&&(ka=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&H("no native wasm support detected");
var la,ma=!1,na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function oa(a,b){for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&na)return na.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|h);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|l:(e&7)<<18|h<<12|l<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c}function t(a){return a?oa(pa,a):""}
function qa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var l=a.charCodeAt(h);if(55296<=l&&57343>=l){var v=a.charCodeAt(++h);l=65536+((l&1023)<<10)|v&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}var ra,w,pa,sa,I,k;
function ta(){var a=la.buffer;ra=a;g.HEAP8=w=new Int8Array(a);g.HEAP16=sa=new Int16Array(a);g.HEAP32=I=new Int32Array(a);g.HEAPU8=pa=new Uint8Array(a);g.HEAPU16=new Uint16Array(a);g.HEAPU32=k=new Uint32Array(a);g.HEAPF32=new Float32Array(a);g.HEAPF64=new Float64Array(a)}var ua,va=[],wa=[],xa=[];function ya(){var a=g.preRun.shift();va.unshift(a)}var J=0,za=null,Aa=null;function Ba(){J++;g.monitorRunDependencies&&g.monitorRunDependencies(J)}
function Ca(){J--;g.monitorRunDependencies&&g.monitorRunDependencies(J);if(0==J&&(null!==za&&(clearInterval(za),za=null),Aa)){var a=Aa;Aa=null;a()}}function H(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";G(a);ma=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function Da(){return K.startsWith("data:application/octet-stream;base64,")}var K;K="out.wasm";if(!Da()){var Ea=K;K=g.locateFile?g.locateFile(Ea,C):C+Ea}
function Fa(){var a=K;try{if(a==K&&ka)return new Uint8Array(ka);if(fa)return fa(a);throw"both async and sync fetching of the wasm failed";}catch(b){H(b)}}
function Ga(){if(!ka&&(ea||z)){if("function"==typeof fetch&&!K.startsWith("file://"))return fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Fa()});if(E)return new Promise(function(a,b){E(K,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Fa()})}var L,Ha;
function Ia(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Pa;"number"==typeof c?void 0===b.ba?ua.get(c)():ua.get(c)(b.ba):c(void 0===b.ba?null:b.ba)}}}
function Ja(a){this.P=a-24;this.za=function(b){k[this.P+4>>2]=b};this.wa=function(b){k[this.P+8>>2]=b};this.xa=function(){I[this.P>>2]=0};this.va=function(){w[this.P+12>>0]=0};this.ya=function(){w[this.P+13>>0]=0};this.T=function(b,c){this.aa();this.za(b);this.wa(c);this.xa();this.va();this.ya()};this.aa=function(){k[this.P+16>>2]=0}}
var Ka=0,La=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},M=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=La(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ma=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Na=
a=>{if("/"===a)return"/";a=M(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function Oa(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(A)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){H("randomDevice")}}
function Pa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=La(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}var Qa=[];function Ra(a,b){Qa[a]={input:[],output:[],V:b};Sa(a,Ta)}
var Ta={open:function(a){var b=Qa[a.node.rdev];if(!b)throw new N(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.V.flush(a.tty)},flush:function(a){a.tty.V.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.V.qa)throw new N(60);for(var e=0,h=0;h<d;h++){try{var l=a.tty.V.qa(a.tty)}catch(v){throw new N(29);}if(void 0===l&&0===e)throw new N(6);if(null===l||void 0===l)break;e++;b[c+h]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.V.ha)throw new N(60);try{for(var e=
0;e<d;e++)a.tty.V.ha(a.tty,b[c+e])}catch(h){throw new N(29);}d&&(a.node.timestamp=Date.now());return e}},Va={qa:function(a){if(!a.input.length){var b=null;if(A){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==
b&&(b+="\n"));if(!b)return null;a.input=Ua(b,!0)}return a.input.shift()},ha:function(a,b){null===b||10===b?(ja(oa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ja(oa(a.output,0)),a.output=[])}},Wa={ha:function(a,b){null===b||10===b?(G(oa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(G(oa(a.output,0)),a.output=[])}},O={J:null,L:function(){return O.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new N(63);O.J||(O.J={dir:{node:{N:O.F.N,I:O.F.I,lookup:O.F.lookup,X:O.F.X,rename:O.F.rename,unlink:O.F.unlink,rmdir:O.F.rmdir,readdir:O.F.readdir,symlink:O.F.symlink},stream:{O:O.G.O}},file:{node:{N:O.F.N,I:O.F.I},stream:{O:O.G.O,read:O.G.read,write:O.G.write,ka:O.G.ka,ga:O.G.ga,ua:O.G.ua}},link:{node:{N:O.F.N,I:O.F.I,readlink:O.F.readlink},stream:{}},ma:{node:{N:O.F.N,I:O.F.I},stream:Xa}});c=Ya(a,b,c,d);16384===(c.mode&61440)?(c.F=O.J.dir.node,
c.G=O.J.dir.stream,c.D={}):32768===(c.mode&61440)?(c.F=O.J.file.node,c.G=O.J.file.stream,c.H=0,c.D=null):40960===(c.mode&61440)?(c.F=O.J.link.node,c.G=O.J.link.stream):8192===(c.mode&61440)&&(c.F=O.J.ma.node,c.G=O.J.ma.stream);c.timestamp=Date.now();a&&(a.D[b]=c,a.timestamp=c.timestamp);return c},Ra:function(a){return a.D?a.D.subarray?a.D.subarray(0,a.H):new Uint8Array(a.D):new Uint8Array(0)},na:function(a,b){var c=a.D?a.D.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,
256)),c=a.D,a.D=new Uint8Array(b),0<a.H&&a.D.set(c.subarray(0,a.H),0))},Ha:function(a,b){if(a.H!=b)if(0==b)a.D=null,a.H=0;else{var c=a.D;a.D=new Uint8Array(b);c&&a.D.set(c.subarray(0,Math.min(b,a.H)));a.H=b}},F:{N:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.H:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);
b.ctime=new Date(a.timestamp);b.Ca=4096;b.blocks=Math.ceil(b.size/b.Ca);return b},I:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.Ha(a,b.size)},lookup:function(){throw Za[44];},X:function(a,b,c,d){return O.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=P(b,c)}catch(h){}if(d)for(var e in d.D)throw new N(55);}delete a.parent.D[a.name];a.parent.timestamp=Date.now();a.name=c;b.D[c]=a;b.timestamp=a.parent.timestamp;
a.parent=b},unlink:function(a,b){delete a.D[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=P(a,b),d;for(d in c.D)throw new N(55);delete a.D[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.D)a.D.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new N(28);return a.link}},G:{read:function(a,b,c,d,e){var h=a.node.D;if(e>=a.node.H)return 0;a=Math.min(a.node.H-
e,d);if(8<a&&h.subarray)b.set(h.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=h[e+d];return a},write:function(a,b,c,d,e,h){b.buffer===w.buffer&&(h=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.D||a.D.subarray)){if(h)return a.D=b.subarray(c,c+d),a.H=d;if(0===a.H&&0===e)return a.D=b.slice(c,c+d),a.H=d;if(e+d<=a.H)return a.D.set(b.subarray(c,c+d),e),d}O.na(a,e+d);if(a.D.subarray&&b.subarray)a.D.set(b.subarray(c,c+d),e);else for(h=0;h<d;h++)a.D[e+h]=b[c+h];a.H=Math.max(a.H,e+
d);return d},O:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.H);if(0>b)throw new N(28);return b},ka:function(a,b,c){O.na(a.node,b+c);a.node.H=Math.max(a.node.H,b+c)},ga:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new N(43);a=a.node.D;if(e&2||a.buffer!==ra){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;H();b=void 0;if(!b)throw new N(48);w.set(a,b)}else c=!1,b=a.byteOffset;return{P:b,Oa:c}},ua:function(a,
b,c,d,e){if(32768!==(a.node.mode&61440))throw new N(43);if(e&2)return 0;O.G.write(a,b,0,d,c,!1);return 0}}};function $a(a,b,c){var d="al "+a;E(a,function(e){e||H('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ca(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ba(d)}
var ab=null,bb={},Q=[],cb=1,R=null,db=!0,N=null,Za={},S=(a,b={})=>{a=Pa("/",a);if(!a)return{path:"",node:null};b=Object.assign({pa:!0,ia:0},b);if(8<b.ia)throw new N(32);a=La(a.split("/").filter(l=>!!l),!1);for(var c=ab,d="/",e=0;e<a.length;e++){var h=e===a.length-1;if(h&&b.parent)break;c=P(c,a[e]);d=M(d+"/"+a[e]);c.W&&(!h||h&&b.pa)&&(c=c.W.root);if(!h||b.da)for(h=0;40960===(c.mode&61440);)if(c=eb(d),d=Pa(Ma(d),c),c=S(d,{ia:b.ia+1}).node,40<h++)throw new N(32);}return{path:d,node:c}},U=a=>{for(var b;;){if(a===
a.parent)return a=a.L.ta,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},fb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length},P=(a,b)=>{var c;if(c=(c=gb(a,"x"))?c:a.F.lookup?0:2)throw new N(c,a);for(c=R[fb(a.id,b)];c;c=c.U){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.F.lookup(a,b)},Ya=(a,b,c,d)=>{a=new hb(a,b,c,d);b=fb(a.parent.id,a.name);a.U=R[b];return R[b]=a},ib={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},jb=
a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},gb=(a,b)=>{if(db)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},kb=(a,b)=>{try{return P(a,b),20}catch(c){}return gb(a,"wx")},lb=(a=0)=>{for(;4096>=a;a++)if(!Q[a])return a;throw new N(33);},nb=(a,b)=>{mb||(mb=function(){this.Y={}},mb.prototype={flags:{get:function(){return this.Y.flags},set:function(c){this.Y.flags=c}},position:{get Qa(){return this.Y.position},
set:function(c){this.Y.position=c}}});a=Object.assign(new mb,a);b=lb(b);a.fd=b;return Q[b]=a},Xa={open:a=>{a.G=bb[a.node.rdev].G;a.G.open&&a.G.open(a)},O:()=>{throw new N(70);}},Sa=(a,b)=>{bb[a]={G:b}},ob=(a,b)=>{var c="/"===b,d=!b;if(c&&ab)throw new N(10);if(!c&&!d){var e=S(b,{pa:!1});b=e.path;e=e.node;if(e.W)throw new N(10);if(16384!==(e.mode&61440))throw new N(54);}b={type:a,Ta:{},ta:b,Ga:[]};a=a.L(b);a.L=b;b.root=a;c?ab=a:e&&(e.W=b,e.L&&e.L.Ga.push(b))},V=(a,b,c)=>{var d=S(a,{parent:!0}).node;
a=Na(a);if(!a||"."===a||".."===a)throw new N(28);var e=kb(d,a);if(e)throw new N(e);if(!d.F.X)throw new N(63);return d.F.X(d,a,b,c)},pb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return V(a,b|8192,c)},qb=(a,b)=>{if(!Pa(a))throw new N(44);var c=S(b,{parent:!0}).node;if(!c)throw new N(44);b=Na(b);var d=kb(c,b);if(d)throw new N(d);if(!c.F.symlink)throw new N(63);c.F.symlink(c,b,a)},rb=a=>{var b=S(a,{parent:!0}).node;if(!b)throw new N(44);var c=Na(a);a=P(b,c);a:{try{var d=P(b,c)}catch(h){d=h.M;break a}var e=
gb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new N(d);if(!b.F.unlink)throw new N(63);if(a.W)throw new N(10);b.F.unlink(b,c);b=fb(a.parent.id,a.name);if(R[b]===a)R[b]=a.U;else for(b=R[b];b;){if(b.U===a){b.U=a.U;break}b=b.U}},eb=a=>{a=S(a).node;if(!a)throw new N(44);if(!a.F.readlink)throw new N(28);return Pa(U(a.parent),a.F.readlink(a))},sb=(a,b)=>{a="string"==typeof a?S(a,{da:!0}).node:a;if(!a.F.I)throw new N(63);a.F.I(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},ub=(a,b,c)=>{if(""===
a)throw new N(44);if("string"==typeof b){var d=ib[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=M(a);try{e=S(a,{da:!(b&131072)}).node}catch(h){}}d=!1;if(b&64)if(e){if(b&128)throw new N(20);}else e=V(a,c,0),d=!0;if(!e)throw new N(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new N(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==
jb(b)||b&512)?31:gb(e,jb(b)):44))throw new N(c);if(b&512&&!d){c=e;c="string"==typeof c?S(c,{da:!0}).node:c;if(!c.F.I)throw new N(63);if(16384===(c.mode&61440))throw new N(31);if(32768!==(c.mode&61440))throw new N(28);if(d=gb(c,"w"))throw new N(d);c.F.I(c,{size:0,timestamp:Date.now()})}b&=-131713;e=nb({node:e,path:U(e),flags:b,seekable:!0,position:0,G:e.G,Na:[],error:!1});e.G.open&&e.G.open(e);!g.logReadFiles||b&1||(tb||(tb={}),a in tb||(tb[a]=1));return e},vb=a=>{if(null===a.fd)throw new N(8);a.ea&&
(a.ea=null);try{a.G.close&&a.G.close(a)}catch(b){throw b;}finally{Q[a.fd]=null}a.fd=null},wb=(a,b,c)=>{if(null===a.fd)throw new N(8);if(!a.seekable||!a.G.O)throw new N(70);if(0!=c&&1!=c&&2!=c)throw new N(28);a.position=a.G.O(a,b,c);a.Na=[]},xb=(a,b,c,d,e,h)=>{if(0>d||0>e)throw new N(28);if(null===a.fd)throw new N(8);if(0===(a.flags&2097155))throw new N(8);if(16384===(a.node.mode&61440))throw new N(31);if(!a.G.write)throw new N(28);a.seekable&&a.flags&1024&&wb(a,0,2);var l="undefined"!=typeof e;if(!l)e=
a.position;else if(!a.seekable)throw new N(70);b=a.G.write(a,b,c,d,e,h);l||(a.position+=b);return b},yb=()=>{N||(N=function(a,b){this.node=b;this.Ia=function(c){this.M=c};this.Ia(a);this.message="FS error"},N.prototype=Error(),N.prototype.constructor=N,[44].forEach(a=>{Za[a]=new N(a);Za[a].stack="<generic error, no stack>"}))},zb,Ab=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Bb=(a,b)=>{a="string"==typeof a?a:U(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=M(a+"/"+c);
try{V(d,16895,0)}catch(e){}a=d}}return d},Cb=(a,b,c,d)=>{a=M(("string"==typeof a?a:U(a))+"/"+b);c=Ab(c,d);return V(a,(void 0!==c?c:438)&4095|32768,0)},Db=(a,b,c,d,e,h)=>{var l=b;a&&(a="string"==typeof a?a:U(a),l=b?M(a+"/"+b):a);a=Ab(d,e);l=V(l,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}sb(l,a|146);b=ub(l,577);xb(b,c,0,c.length,0,h);vb(b);sb(l,a)}return l},W=(a,b,c,d)=>{a=M(("string"==typeof a?a:U(a))+"/"+b);b=
Ab(!!c,!!d);W.sa||(W.sa=64);var e=W.sa++<<8|0;Sa(e,{open:h=>{h.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(h,l,v,r)=>{for(var p=0,m=0;m<r;m++){try{var u=c()}catch(x){throw new N(29);}if(void 0===u&&0===p)throw new N(6);if(null===u||void 0===u)break;p++;l[v+m]=u}p&&(h.node.timestamp=Date.now());return p},write:(h,l,v,r)=>{for(var p=0;p<r;p++)try{d(l[v+p])}catch(m){throw new N(29);}r&&(h.node.timestamp=Date.now());return p}});return pb(a,b,e)},Eb=a=>{if(!(a.Ea||a.Fa||a.link||
a.D)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(D)try{a.D=Ua(D(a.url),!0),a.H=a.D.length}catch(b){throw new N(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},Fb=(a,b,c,d,e)=>{function h(){this.fa=!1;this.T=[]}h.prototype.get=function(m){if(!(m>this.length-1||0>m)){var u=
m%this.chunkSize;return this.ra(m/this.chunkSize|0)[u]}};h.prototype.aa=function(m){this.ra=m};h.prototype.la=function(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);var u=Number(m.getResponseHeader("Content-length")),x,f=(x=m.getResponseHeader("Accept-Ranges"))&&"bytes"===x;m=(x=m.getResponseHeader("Content-Encoding"))&&"gzip"===x;var n=1048576;f||(n=u);var q=this;q.aa(y=>{var F=y*
n,T=(y+1)*n-1;T=Math.min(T,u-1);if("undefined"==typeof q.T[y]){var Wb=q.T;if(F>T)throw Error("invalid range ("+F+", "+T+") or no bytes requested!");if(T>u-1)throw Error("only "+u+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",c,!1);u!==n&&B.setRequestHeader("Range","bytes="+F+"-"+T);B.responseType="arraybuffer";B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>B.status||304===B.status))throw Error("Couldn't load "+
c+". Status: "+B.status);F=void 0!==B.response?new Uint8Array(B.response||[]):Ua(B.responseText||"",!0);Wb[y]=F}if("undefined"==typeof q.T[y])throw Error("doXHR failed!");return q.T[y]});if(m||!u)n=u=1,n=u=this.ra(0).length,ja("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ba=u;this.Aa=n;this.fa=!0};if("undefined"!=typeof XMLHttpRequest){if(!z)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var l=new h;Object.defineProperties(l,{length:{get:function(){this.fa||this.la();return this.Ba}},chunkSize:{get:function(){this.fa||this.la();return this.Aa}}});var v=void 0}else v=c,l=void 0;var r=Cb(a,b,d,e);l?r.D=l:v&&(r.D=null,r.url=v);Object.defineProperties(r,{H:{get:function(){return this.D.length}}});var p={};Object.keys(r.G).forEach(m=>{var u=r.G[m];p[m]=function(){Eb(r);return u.apply(null,arguments)}});p.read=(m,u,x,f,n)=>{Eb(r);m=m.node.D;if(n>=m.length)u=0;else{f=Math.min(m.length-n,
f);if(m.slice)for(var q=0;q<f;q++)u[x+q]=m[n+q];else for(q=0;q<f;q++)u[x+q]=m.get(n+q);u=f}return u};p.ga=()=>{Eb(r);H();throw new N(48);};r.G=p;return r},Hb=(a,b,c,d,e,h,l,v,r,p)=>{function m(f){function n(q){p&&p();v||Db(a,b,q,d,e,r);h&&h();Ca(x)}Gb.Sa(f,u,n,()=>{l&&l();Ca(x)})||n(f)}var u=b?Pa(M(a+"/"+b)):a,x="cp "+u;Ba(x);"string"==typeof c?$a(c,f=>m(f),l):m(c)},X={},mb,tb,Ib=void 0;function Y(){Ib+=4;return I[Ib-4>>2]}function Z(a){a=Q[a];if(!a)throw new N(8);return a}var Jb;
Jb=A?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var Kb={};function Lb(){if(!Mb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Kb)void 0===Kb[b]?delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Mb=c}return Mb}var Mb;function Nb(a){return 0===a%4&&(0!==a%100||0===a%400)}
var Ob=[31,29,31,30,31,30,31,31,30,31,30,31],Pb=[31,28,31,30,31,30,31,31,30,31,30,31];
function Qb(a,b,c,d){function e(f,n,q){for(f="number"==typeof f?f.toString():f||"";f.length<n;)f=q[0]+f;return f}function h(f,n){return e(f,n,"0")}function l(f,n){function q(F){return 0>F?-1:0<F?1:0}var y;0===(y=q(f.getFullYear()-n.getFullYear()))&&0===(y=q(f.getMonth()-n.getMonth()))&&(y=q(f.getDate()-n.getDate()));return y}function v(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function r(f){var n=f.R;for(f=new Date((new Date(f.S+1900,0,1)).getTime());0<n;){var q=f.getMonth(),y=(Nb(f.getFullYear())?Ob:Pb)[q];if(n>y-f.getDate())n-=y-f.getDate()+1,f.setDate(1),11>q?f.setMonth(q+1):(f.setMonth(0),f.setFullYear(f.getFullYear()+1));else{f.setDate(f.getDate()+n);break}}q=new Date(f.getFullYear()+1,0,4);n=v(new Date(f.getFullYear(),0,
4));q=v(q);return 0>=l(n,f)?0>=l(q,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var p=I[d+40>>2];d={La:I[d>>2],Ka:I[d+4>>2],Z:I[d+8>>2],ja:I[d+12>>2],$:I[d+16>>2],S:I[d+20>>2],K:I[d+24>>2],R:I[d+28>>2],Ua:I[d+32>>2],Ja:I[d+36>>2],Ma:p?t(p):""};c=t(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var m in p)c=c.replace(new RegExp(m,"g"),p[m]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),x="January February March April May June July August September October November December".split(" ");p={"%a":function(f){return u[f.K].substring(0,3)},"%A":function(f){return u[f.K]},"%b":function(f){return x[f.$].substring(0,3)},"%B":function(f){return x[f.$]},
"%C":function(f){return h((f.S+1900)/100|0,2)},"%d":function(f){return h(f.ja,2)},"%e":function(f){return e(f.ja,2," ")},"%g":function(f){return r(f).toString().substring(2)},"%G":function(f){return r(f)},"%H":function(f){return h(f.Z,2)},"%I":function(f){f=f.Z;0==f?f=12:12<f&&(f-=12);return h(f,2)},"%j":function(f){for(var n=0,q=0;q<=f.$-1;n+=(Nb(f.S+1900)?Ob:Pb)[q++]);return h(f.ja+n,3)},"%m":function(f){return h(f.$+1,2)},"%M":function(f){return h(f.Ka,2)},"%n":function(){return"\n"},"%p":function(f){return 0<=
f.Z&&12>f.Z?"AM":"PM"},"%S":function(f){return h(f.La,2)},"%t":function(){return"\t"},"%u":function(f){return f.K||7},"%U":function(f){return h(Math.floor((f.R+7-f.K)/7),2)},"%V":function(f){var n=Math.floor((f.R+7-(f.K+6)%7)/7);2>=(f.K+371-f.R-2)%7&&n++;if(n)53==n&&(q=(f.K+371-f.R)%7,4==q||3==q&&Nb(f.S)||(n=1));else{n=52;var q=(f.K+7-f.R-1)%7;(4==q||5==q&&Nb(f.S%400-1))&&n++}return h(n,2)},"%w":function(f){return f.K},"%W":function(f){return h(Math.floor((f.R+7-(f.K+6)%7)/7),2)},"%y":function(f){return(f.S+
1900).toString().substring(2)},"%Y":function(f){return f.S+1900},"%z":function(f){f=f.Ja;var n=0<=f;f=Math.abs(f)/60;return(n?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.Ma},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(m in p)c.includes(m)&&(c=c.replace(new RegExp(m,"g"),p[m](d)));c=c.replace(/\0\0/g,"%");m=Ua(c,!1);if(m.length>b)return 0;w.set(m,a);return m.length-1}
function hb(a,b,c,d){a||(a=this);this.parent=a;this.L=a.L;this.W=null;this.id=cb++;this.name=b;this.mode=c;this.F={};this.G={};this.rdev=d}Object.defineProperties(hb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Fa:{get:function(){return 16384===(this.mode&61440)}},Ea:{get:function(){return 8192===(this.mode&61440)}}});yb();R=Array(4096);
ob(O,"/");V("/tmp",16895,0);V("/home",16895,0);V("/home/web_user",16895,0);(()=>{V("/dev",16895,0);Sa(259,{read:()=>0,write:(b,c,d,e)=>e});pb("/dev/null",259);Ra(1280,Va);Ra(1536,Wa);pb("/dev/tty",1280);pb("/dev/tty1",1536);var a=Oa();W("/dev","random",a);W("/dev","urandom",a);V("/dev/shm",16895,0);V("/dev/shm/tmp",16895,0)})();
(()=>{V("/proc",16895,0);var a=V("/proc/self",16895,0);V("/proc/self/fd",16895,0);ob({L:()=>{var b=Ya(a,"fd",16895,73);b.F={lookup:(c,d)=>{var e=Q[+d];if(!e)throw new N(8);c={parent:null,L:{ta:"fake"},F:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();var Gb;g.FS_createPath=Bb;g.FS_createDataFile=Db;g.FS_createPreloadedFile=Hb;g.FS_unlink=rb;g.FS_createLazyFile=Fb;g.FS_createDevice=W;
function Ua(a,b){for(var c=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++c:c=2047>=e?c+2:65535>=e?c+3:c+4}c=Array(c+1);a=qa(a,c,0,c.length);b&&(c.length=a);return c}
var Tb={b:function(a){return Rb(a+24)+24},a:function(a,b,c){(new Ja(a)).T(b,c);Ka++;throw a;},h:function(a,b,c){Ib=c;try{var d=Z(a);switch(b){case 0:var e=Y();return 0>e?-28:nb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Y(),d.flags|=e,0;case 5:return e=Y(),sa[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return I[Sb()>>2]=28,-1;default:return-28}}catch(h){if("undefined"==typeof X||!(h instanceof N))throw h;return-h.M}},j:function(a,b,c){Ib=c;try{var d=
Z(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=Y();return I[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=Y();if(!d.G.Da)throw new N(59);return d.G.Da(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:H("bad ioctl syscall "+b)}}catch(h){if("undefined"==typeof X||!(h instanceof N))throw h;return-h.M}},g:function(a,b,c,d){Ib=d;try{b=t(b);
var e=b;if("/"===e.charAt(0))b=e;else{if(-100===a)var h="/";else{var l=Q[a];if(!l)throw new N(8);h=l.path}if(0==e.length)throw new N(44);b=M(h+"/"+e)}var v=d?Y():0;return ub(b,c,v).fd}catch(r){if("undefined"==typeof X||!(r instanceof N))throw r;return-r.M}},m:function(){return Date.now()},l:function(){return!0},d:function(){H("")},p:function(){return 2147483648},k:Jb,e:function(a){var b=pa.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=
Math;d=Math.max(a,d);e=e.min.call(e,2147483648,d+(65536-d%65536)%65536);a:{try{la.grow(e-ra.byteLength+65535>>>16);ta();var h=1;break a}catch(l){}h=void 0}if(h)return!0}return!1},q:function(a,b){var c=0;Lb().forEach(function(d,e){var h=b+c;e=k[a+4*e>>2]=h;for(h=0;h<d.length;++h)w[e++>>0]=d.charCodeAt(h);w[e>>0]=0;c+=d.length+1});return 0},r:function(a,b){var c=Lb();k[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});k[b>>2]=d;return 0},c:function(a){try{var b=Z(a);vb(b);return 0}catch(c){if("undefined"==
typeof X||!(c instanceof N))throw c;return c.M}},f:function(a,b,c,d){try{a:{var e=Z(a);a=b;for(var h=b=0;h<c;h++){var l=k[a>>2],v=k[a+4>>2];a+=8;var r=e,p=l,m=v,u=void 0,x=w;if(0>m||0>u)throw new N(28);if(null===r.fd)throw new N(8);if(1===(r.flags&2097155))throw new N(8);if(16384===(r.node.mode&61440))throw new N(31);if(!r.G.read)throw new N(28);var f="undefined"!=typeof u;if(!f)u=r.position;else if(!r.seekable)throw new N(70);var n=r.G.read(r,x,p,m,u);f||(r.position+=n);var q=n;if(0>q){var y=-1;
break a}b+=q;if(q<v)break}y=b}I[d>>2]=y;return 0}catch(F){if("undefined"==typeof X||!(F instanceof N))throw F;return F.M}},n:function(a,b,c,d,e){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var h=Z(a);wb(h,b,d);Ha=[h.position>>>0,(L=h.position,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];I[e>>2]=Ha[0];I[e+4>>2]=Ha[1];h.ea&&0===b&&0===d&&(h.ea=null);return 0}catch(l){if("undefined"==typeof X||
!(l instanceof N))throw l;return l.M}},i:function(a,b,c,d){try{a:{var e=Z(a);a=b;for(var h=b=0;h<c;h++){var l=k[a>>2],v=k[a+4>>2];a+=8;var r=xb(e,w,l,v);if(0>r){var p=-1;break a}b+=r}p=b}k[d>>2]=p;return 0}catch(m){if("undefined"==typeof X||!(m instanceof N))throw m;return m.M}},o:function(a,b,c,d){return Qb(a,b,c,d)}};
(function(){function a(e){g.asm=e.exports;la=g.asm.s;ta();ua=g.asm.w;wa.unshift(g.asm.t);Ca("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Ga().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(e,function(h){G("failed to asynchronously prepare wasm: "+h);H(h)})}var d={a:Tb};Ba("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return G("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ka||
"function"!=typeof WebAssembly.instantiateStreaming||Da()||K.startsWith("file://")||A||"function"!=typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(h){G("wasm streaming compile failed: "+h);G("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.t).apply(null,arguments)};
g._allocateBuffer=function(){return(g._allocateBuffer=g.asm.u).apply(null,arguments)};g._detectCode=function(){return(g._detectCode=g.asm.v).apply(null,arguments)};
var Rb=g._malloc=function(){return(Rb=g._malloc=g.asm.x).apply(null,arguments)},Sb=g.___errno_location=function(){return(Sb=g.___errno_location=g.asm.y).apply(null,arguments)},Ub=g.stackSave=function(){return(Ub=g.stackSave=g.asm.z).apply(null,arguments)},Vb=g.stackRestore=function(){return(Vb=g.stackRestore=g.asm.A).apply(null,arguments)},Xb=g.stackAlloc=function(){return(Xb=g.stackAlloc=g.asm.B).apply(null,arguments)};
g.___cxa_is_pointer_type=function(){return(g.___cxa_is_pointer_type=g.asm.C).apply(null,arguments)};g.___emscripten_embedded_file_data=1295120;
g.ccall=function(a,b,c,d){var e={string:function(p){var m=0;if(null!==p&&void 0!==p&&0!==p){var u=(p.length<<2)+1;m=Xb(u);qa(p,pa,m,u)}return m},array:function(p){var m=Xb(p.length);w.set(p,m);return m}};a=g["_"+a];var h=[],l=0;if(d)for(var v=0;v<d.length;v++){var r=e[c[v]];r?(0===l&&(l=Ub()),h[v]=r(d[v])):h[v]=d[v]}c=a.apply(null,h);return c=function(p){0!==l&&Vb(l);return"string"===b?t(p):"boolean"===b?!!p:p}(c)};g.addRunDependency=Ba;g.removeRunDependency=Ca;g.FS_createPath=Bb;
g.FS_createDataFile=Db;g.FS_createPreloadedFile=Hb;g.FS_createLazyFile=Fb;g.FS_createDevice=W;g.FS_unlink=rb;var Yb;Aa=function Zb(){Yb||$b();Yb||(Aa=Zb)};
function $b(){function a(){if(!Yb&&(Yb=!0,g.calledRun=!0,!ma)){g.noFSInit||zb||(zb=!0,yb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?W("/dev","stdin",g.stdin):qb("/dev/tty","/dev/stdin"),g.stdout?W("/dev","stdout",null,g.stdout):qb("/dev/tty","/dev/stdout"),g.stderr?W("/dev","stderr",null,g.stderr):qb("/dev/tty1","/dev/stderr"),ub("/dev/stdin",0),ub("/dev/stdout",1),ub("/dev/stderr",1));db=!1;Ia(wa);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();xa.unshift(b)}Ia(xa)}}if(!(0<J)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ya();Ia(va);0<J||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=$b;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();$b();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
