
var Module = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});g.ja||(g.ja=0);g.ja++;g.ENVIRONMENT_IS_PTHREAD||function(){function a(){g.FS_createPath("/","model",!0,!0);var b=g.___emscripten_embedded_file_data>>2;do{var c=k[b++],d=k[b++],e=k[b++];c=t(c);g.FS_createDataFile(c,null,w.subarray(e,e+d),!0,!0,!0)}while(k[b])}g.calledRun?a():(g.preRun||(g.preRun=[]),g.preRun.push(a))}({files:[]});
var ca=Object.assign({},g),da="./this.program",ea="object"==typeof window,z="function"==typeof importScripts,A="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,C="",D,F,fa,fs,ha,ia;
if(A)C=z?require("path").dirname(C)+"/":__dirname+"/",ia=()=>{ha||(fs=require("fs"),ha=require("path"))},D=function(a,b){ia();a=ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},fa=a=>{a=D(a,!0);a.buffer||(a=new Uint8Array(a));return a},F=(a,b,c)=>{ia();a=ha.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",
function(a){throw a;}),g.inspect=function(){return"[Emscripten Module object]"};else if(ea||z)z?C=self.location.href:"undefined"!=typeof document&&document.currentScript&&(C=document.currentScript.src),_scriptDir&&(C=_scriptDir),0!==C.indexOf("blob:")?C=C.substr(0,C.replace(/[?#].*/,"").lastIndexOf("/")+1):C="",D=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},z&&(fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
F=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ja=g.print||console.log.bind(console),G=g.printErr||console.warn.bind(console);Object.assign(g,ca);ca=null;g.thisProgram&&(da=g.thisProgram);var ka;g.wasmBinary&&(ka=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&H("no native wasm support detected");
var la,ma=!1,na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function oa(a,b){for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&na)return na.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|h);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|l:(e&7)<<18|h<<12|l<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c}function t(a){return a?oa(pa,a):""}
function qa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var l=a.charCodeAt(h);if(55296<=l&&57343>=l){var v=a.charCodeAt(++h);l=65536+((l&1023)<<10)|v&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}var ra,w,pa,sa,I,k;
function ta(){var a=la.buffer;ra=a;g.HEAP8=w=new Int8Array(a);g.HEAP16=sa=new Int16Array(a);g.HEAP32=I=new Int32Array(a);g.HEAPU8=pa=new Uint8Array(a);g.HEAPU16=new Uint16Array(a);g.HEAPU32=k=new Uint32Array(a);g.HEAPF32=new Float32Array(a);g.HEAPF64=new Float64Array(a)}var ua,va=[],wa=[],xa=[];function ya(){var a=g.preRun.shift();va.unshift(a)}var J=0,za=null,Aa=null;function Ba(){J++;g.monitorRunDependencies&&g.monitorRunDependencies(J)}
function Ca(){J--;g.monitorRunDependencies&&g.monitorRunDependencies(J);if(0==J&&(null!==za&&(clearInterval(za),za=null),Aa)){var a=Aa;Aa=null;a()}}function H(a){if(g.onAbort)g.onAbort(a);G("Aborted("+a+")");ma=!0;Da()}function Ea(){return K.startsWith("data:application/octet-stream;base64,")}var K;K="out.wasm";if(!Ea()){var Fa=K;K=g.locateFile?g.locateFile(Fa,C):C+Fa}
function Ga(){var a=K;try{if(a==K&&ka)return new Uint8Array(ka);if(fa)return fa(a);throw"both async and sync fetching of the wasm failed";}catch(b){H(b)}}
function Ha(){if(!ka&&(ea||z)){if("function"==typeof fetch&&!K.startsWith("file://"))return fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Ga()});if(F)return new Promise(function(a,b){F(K,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ga()})}var L,Ia;
function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Ga;"number"==typeof c?void 0===b.X?ua.get(c)():ua.get(c)(b.X):c(void 0===b.X?null:b.X)}}}
var Ka=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},M=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ka(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},La=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Ma=a=>{if("/"===
a)return"/";a=M(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function Na(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(A)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){H("randomDevice")}}
function Oa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ka(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}var Pa=[];function Qa(a,b){Pa[a]={input:[],output:[],P:b};Ra(a,Sa)}
var Sa={open:function(a){var b=Pa[a.node.rdev];if(!b)throw new N(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.P.flush(a.tty)},flush:function(a){a.tty.P.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.P.la)throw new N(60);for(var e=0,h=0;h<d;h++){try{var l=a.tty.P.la(a.tty)}catch(v){throw new N(29);}if(void 0===l&&0===e)throw new N(6);if(null===l||void 0===l)break;e++;b[c+h]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.P.ba)throw new N(60);try{for(var e=
0;e<d;e++)a.tty.P.ba(a.tty,b[c+e])}catch(h){throw new N(29);}d&&(a.node.timestamp=Date.now());return e}},Ua={la:function(a){if(!a.input.length){var b=null;if(A){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==
b&&(b+="\n"));if(!b)return null;a.input=Ta(b,!0)}return a.input.shift()},ba:function(a,b){null===b||10===b?(ja(oa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ja(oa(a.output,0)),a.output=[])}},Va={ba:function(a,b){null===b||10===b?(G(oa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(G(oa(a.output,0)),a.output=[])}},O={G:null,I:function(){return O.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new N(63);O.G||(O.G={dir:{node:{K:O.B.K,F:O.B.F,lookup:O.B.lookup,T:O.B.T,rename:O.B.rename,unlink:O.B.unlink,rmdir:O.B.rmdir,readdir:O.B.readdir,symlink:O.B.symlink},stream:{L:O.C.L}},file:{node:{K:O.B.K,F:O.B.F},stream:{L:O.C.L,read:O.C.read,write:O.C.write,fa:O.C.fa,aa:O.C.aa,pa:O.C.pa}},link:{node:{K:O.B.K,F:O.B.F,readlink:O.B.readlink},stream:{}},ha:{node:{K:O.B.K,F:O.B.F},stream:Wa}});c=Xa(a,b,c,d);16384===(c.mode&61440)?(c.B=O.G.dir.node,
c.C=O.G.dir.stream,c.A={}):32768===(c.mode&61440)?(c.B=O.G.file.node,c.C=O.G.file.stream,c.D=0,c.A=null):40960===(c.mode&61440)?(c.B=O.G.link.node,c.C=O.G.link.stream):8192===(c.mode&61440)&&(c.B=O.G.ha.node,c.C=O.G.ha.stream);c.timestamp=Date.now();a&&(a.A[b]=c,a.timestamp=c.timestamp);return c},Ia:function(a){return a.A?a.A.subarray?a.A.subarray(0,a.D):new Uint8Array(a.A):new Uint8Array(0)},ia:function(a,b){var c=a.A?a.A.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,
256)),c=a.A,a.A=new Uint8Array(b),0<a.D&&a.A.set(c.subarray(0,a.D),0))},ya:function(a,b){if(a.D!=b)if(0==b)a.A=null,a.D=0;else{var c=a.A;a.A=new Uint8Array(b);c&&a.A.set(c.subarray(0,Math.min(b,a.D)));a.D=b}},B:{K:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.D:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);
b.ctime=new Date(a.timestamp);b.ta=4096;b.blocks=Math.ceil(b.size/b.ta);return b},F:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.ya(a,b.size)},lookup:function(){throw Ya[44];},T:function(a,b,c,d){return O.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=P(b,c)}catch(h){}if(d)for(var e in d.A)throw new N(55);}delete a.parent.A[a.name];a.parent.timestamp=Date.now();a.name=c;b.A[c]=a;b.timestamp=a.parent.timestamp;
a.parent=b},unlink:function(a,b){delete a.A[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=P(a,b),d;for(d in c.A)throw new N(55);delete a.A[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.A)a.A.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new N(28);return a.link}},C:{read:function(a,b,c,d,e){var h=a.node.A;if(e>=a.node.D)return 0;a=Math.min(a.node.D-
e,d);if(8<a&&h.subarray)b.set(h.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=h[e+d];return a},write:function(a,b,c,d,e,h){b.buffer===w.buffer&&(h=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.A||a.A.subarray)){if(h)return a.A=b.subarray(c,c+d),a.D=d;if(0===a.D&&0===e)return a.A=b.slice(c,c+d),a.D=d;if(e+d<=a.D)return a.A.set(b.subarray(c,c+d),e),d}O.ia(a,e+d);if(a.A.subarray&&b.subarray)a.A.set(b.subarray(c,c+d),e);else for(h=0;h<d;h++)a.A[e+h]=b[c+h];a.D=Math.max(a.D,e+
d);return d},L:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.D);if(0>b)throw new N(28);return b},fa:function(a,b,c){O.ia(a.node,b+c);a.node.D=Math.max(a.node.D,b+c)},aa:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new N(43);a=a.node.A;if(e&2||a.buffer!==ra){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;H();b=void 0;if(!b)throw new N(48);w.set(a,b)}else c=!1,b=a.byteOffset;return{La:b,Fa:c}},pa:function(a,
b,c,d,e){if(32768!==(a.node.mode&61440))throw new N(43);if(e&2)return 0;O.C.write(a,b,0,d,c,!1);return 0}}};function Za(a,b,c){var d="al "+a;F(a,function(e){e||H('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ca(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ba(d)}
var $a=null,ab={},Q=[],bb=1,R=null,cb=!0,N=null,Ya={},S=(a,b={})=>{a=Oa("/",a);if(!a)return{path:"",node:null};b=Object.assign({ka:!0,da:0},b);if(8<b.da)throw new N(32);a=Ka(a.split("/").filter(l=>!!l),!1);for(var c=$a,d="/",e=0;e<a.length;e++){var h=e===a.length-1;if(h&&b.parent)break;c=P(c,a[e]);d=M(d+"/"+a[e]);c.R&&(!h||h&&b.ka)&&(c=c.R.root);if(!h||b.Y)for(h=0;40960===(c.mode&61440);)if(c=db(d),d=Oa(La(d),c),c=S(d,{da:b.da+1}).node,40<h++)throw new N(32);}return{path:d,node:c}},U=a=>{for(var b;;){if(a===
a.parent)return a=a.I.oa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},eb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length},P=(a,b)=>{var c;if(c=(c=fb(a,"x"))?c:a.B.lookup?0:2)throw new N(c,a);for(c=R[eb(a.id,b)];c;c=c.O){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.B.lookup(a,b)},Xa=(a,b,c,d)=>{a=new gb(a,b,c,d);b=eb(a.parent.id,a.name);a.O=R[b];return R[b]=a},hb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},ib=
a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},fb=(a,b)=>{if(cb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},jb=(a,b)=>{try{return P(a,b),20}catch(c){}return fb(a,"wx")},kb=(a=0)=>{for(;4096>=a;a++)if(!Q[a])return a;throw new N(33);},mb=(a,b)=>{lb||(lb=function(){this.U={}},lb.prototype={flags:{get:function(){return this.U.flags},set:function(c){this.U.flags=c}},position:{get Ha(){return this.U.position},
set:function(c){this.U.position=c}}});a=Object.assign(new lb,a);b=kb(b);a.fd=b;return Q[b]=a},Wa={open:a=>{a.C=ab[a.node.rdev].C;a.C.open&&a.C.open(a)},L:()=>{throw new N(70);}},Ra=(a,b)=>{ab[a]={C:b}},nb=(a,b)=>{var c="/"===b,d=!b;if(c&&$a)throw new N(10);if(!c&&!d){var e=S(b,{ka:!1});b=e.path;e=e.node;if(e.R)throw new N(10);if(16384!==(e.mode&61440))throw new N(54);}b={type:a,Ka:{},oa:b,xa:[]};a=a.I(b);a.I=b;b.root=a;c?$a=a:e&&(e.R=b,e.I&&e.I.xa.push(b))},V=(a,b,c)=>{var d=S(a,{parent:!0}).node;
a=Ma(a);if(!a||"."===a||".."===a)throw new N(28);var e=jb(d,a);if(e)throw new N(e);if(!d.B.T)throw new N(63);return d.B.T(d,a,b,c)},ob=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return V(a,b|8192,c)},pb=(a,b)=>{if(!Oa(a))throw new N(44);var c=S(b,{parent:!0}).node;if(!c)throw new N(44);b=Ma(b);var d=jb(c,b);if(d)throw new N(d);if(!c.B.symlink)throw new N(63);c.B.symlink(c,b,a)},qb=a=>{var b=S(a,{parent:!0}).node;if(!b)throw new N(44);var c=Ma(a);a=P(b,c);a:{try{var d=P(b,c)}catch(h){d=h.J;break a}var e=
fb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new N(d);if(!b.B.unlink)throw new N(63);if(a.R)throw new N(10);b.B.unlink(b,c);b=eb(a.parent.id,a.name);if(R[b]===a)R[b]=a.O;else for(b=R[b];b;){if(b.O===a){b.O=a.O;break}b=b.O}},db=a=>{a=S(a).node;if(!a)throw new N(44);if(!a.B.readlink)throw new N(28);return Oa(U(a.parent),a.B.readlink(a))},rb=(a,b)=>{a="string"==typeof a?S(a,{Y:!0}).node:a;if(!a.B.F)throw new N(63);a.B.F(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},tb=(a,b,c)=>{if(""===
a)throw new N(44);if("string"==typeof b){var d=hb[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=M(a);try{e=S(a,{Y:!(b&131072)}).node}catch(h){}}d=!1;if(b&64)if(e){if(b&128)throw new N(20);}else e=V(a,c,0),d=!0;if(!e)throw new N(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new N(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==ib(b)||
b&512)?31:fb(e,ib(b)):44))throw new N(c);if(b&512&&!d){c=e;c="string"==typeof c?S(c,{Y:!0}).node:c;if(!c.B.F)throw new N(63);if(16384===(c.mode&61440))throw new N(31);if(32768!==(c.mode&61440))throw new N(28);if(d=fb(c,"w"))throw new N(d);c.B.F(c,{size:0,timestamp:Date.now()})}b&=-131713;e=mb({node:e,path:U(e),flags:b,seekable:!0,position:0,C:e.C,Ea:[],error:!1});e.C.open&&e.C.open(e);!g.logReadFiles||b&1||(sb||(sb={}),a in sb||(sb[a]=1));return e},ub=a=>{if(null===a.fd)throw new N(8);a.Z&&(a.Z=null);
try{a.C.close&&a.C.close(a)}catch(b){throw b;}finally{Q[a.fd]=null}a.fd=null},vb=(a,b,c)=>{if(null===a.fd)throw new N(8);if(!a.seekable||!a.C.L)throw new N(70);if(0!=c&&1!=c&&2!=c)throw new N(28);a.position=a.C.L(a,b,c);a.Ea=[]},wb=(a,b,c,d,e,h)=>{if(0>d||0>e)throw new N(28);if(null===a.fd)throw new N(8);if(0===(a.flags&2097155))throw new N(8);if(16384===(a.node.mode&61440))throw new N(31);if(!a.C.write)throw new N(28);a.seekable&&a.flags&1024&&vb(a,0,2);var l="undefined"!=typeof e;if(!l)e=a.position;
else if(!a.seekable)throw new N(70);b=a.C.write(a,b,c,d,e,h);l||(a.position+=b);return b},xb=()=>{N||(N=function(a,b){this.node=b;this.za=function(c){this.J=c};this.za(a);this.message="FS error"},N.prototype=Error(),N.prototype.constructor=N,[44].forEach(a=>{Ya[a]=new N(a);Ya[a].stack="<generic error, no stack>"}))},yb,zb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ab=(a,b)=>{a="string"==typeof a?a:U(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=M(a+"/"+c);try{V(d,16895,
0)}catch(e){}a=d}}return d},Bb=(a,b,c,d)=>{a=M(("string"==typeof a?a:U(a))+"/"+b);c=zb(c,d);return V(a,(void 0!==c?c:438)&4095|32768,0)},Cb=(a,b,c,d,e,h)=>{var l=b;a&&(a="string"==typeof a?a:U(a),l=b?M(a+"/"+b):a);a=zb(d,e);l=V(l,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}rb(l,a|146);b=tb(l,577);wb(b,c,0,c.length,0,h);ub(b);rb(l,a)}return l},W=(a,b,c,d)=>{a=M(("string"==typeof a?a:U(a))+"/"+b);b=zb(!!c,!!d);W.na||
(W.na=64);var e=W.na++<<8|0;Ra(e,{open:h=>{h.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(h,l,v,r)=>{for(var p=0,m=0;m<r;m++){try{var u=c()}catch(x){throw new N(29);}if(void 0===u&&0===p)throw new N(6);if(null===u||void 0===u)break;p++;l[v+m]=u}p&&(h.node.timestamp=Date.now());return p},write:(h,l,v,r)=>{for(var p=0;p<r;p++)try{d(l[v+p])}catch(m){throw new N(29);}r&&(h.node.timestamp=Date.now());return p}});return ob(a,b,e)},Db=a=>{if(!(a.va||a.wa||a.link||a.A)){if("undefined"!=
typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(D)try{a.A=Ta(D(a.url),!0),a.D=a.A.length}catch(b){throw new N(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}},Eb=(a,b,c,d,e)=>{function h(){this.$=!1;this.S=[]}h.prototype.get=function(m){if(!(m>this.length-1||0>m)){var u=m%this.chunkSize;return this.ma(m/
this.chunkSize|0)[u]}};h.prototype.qa=function(m){this.ma=m};h.prototype.ga=function(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);var u=Number(m.getResponseHeader("Content-length")),x,f=(x=m.getResponseHeader("Accept-Ranges"))&&"bytes"===x;m=(x=m.getResponseHeader("Content-Encoding"))&&"gzip"===x;var n=1048576;f||(n=u);var q=this;q.qa(y=>{var E=y*n,T=(y+1)*n-1;T=Math.min(T,u-1);if("undefined"==
typeof q.S[y]){var Ub=q.S;if(E>T)throw Error("invalid range ("+E+", "+T+") or no bytes requested!");if(T>u-1)throw Error("only "+u+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",c,!1);u!==n&&B.setRequestHeader("Range","bytes="+E+"-"+T);B.responseType="arraybuffer";B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>B.status||304===B.status))throw Error("Couldn't load "+c+". Status: "+B.status);E=void 0!==B.response?
new Uint8Array(B.response||[]):Ta(B.responseText||"",!0);Ub[y]=E}if("undefined"==typeof q.S[y])throw Error("doXHR failed!");return q.S[y]});if(m||!u)n=u=1,n=u=this.ma(0).length,ja("LazyFiles on gzip forces download of the whole file when length is accessed");this.sa=u;this.ra=n;this.$=!0};if("undefined"!=typeof XMLHttpRequest){if(!z)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new h;Object.defineProperties(l,{length:{get:function(){this.$||
this.ga();return this.sa}},chunkSize:{get:function(){this.$||this.ga();return this.ra}}});var v=void 0}else v=c,l=void 0;var r=Bb(a,b,d,e);l?r.A=l:v&&(r.A=null,r.url=v);Object.defineProperties(r,{D:{get:function(){return this.A.length}}});var p={};Object.keys(r.C).forEach(m=>{var u=r.C[m];p[m]=function(){Db(r);return u.apply(null,arguments)}});p.read=(m,u,x,f,n)=>{Db(r);m=m.node.A;if(n>=m.length)u=0;else{f=Math.min(m.length-n,f);if(m.slice)for(var q=0;q<f;q++)u[x+q]=m[n+q];else for(q=0;q<f;q++)u[x+
q]=m.get(n+q);u=f}return u};p.aa=()=>{Db(r);H();throw new N(48);};r.C=p;return r},Gb=(a,b,c,d,e,h,l,v,r,p)=>{function m(f){function n(q){p&&p();v||Cb(a,b,q,d,e,r);h&&h();Ca(x)}Fb.Ja(f,u,n,()=>{l&&l();Ca(x)})||n(f)}var u=b?Oa(M(a+"/"+b)):a,x="cp "+u;Ba(x);"string"==typeof c?Za(c,f=>m(f),l):m(c)},X={},lb,sb,Hb=void 0;function Y(){Hb+=4;return I[Hb-4>>2]}function Z(a){a=Q[a];if(!a)throw new N(8);return a}var Ib;Ib=A?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var Jb={};
function Kb(){if(!Lb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Jb)void 0===Jb[b]?delete a[b]:a[b]=Jb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Lb=c}return Lb}var Lb;function Mb(a){return 0===a%4&&(0!==a%100||0===a%400)}var Nb=[31,29,31,30,31,30,31,31,30,31,30,31],Ob=[31,28,31,30,31,30,31,31,30,31,30,31];
function Pb(a,b,c,d){function e(f,n,q){for(f="number"==typeof f?f.toString():f||"";f.length<n;)f=q[0]+f;return f}function h(f,n){return e(f,n,"0")}function l(f,n){function q(E){return 0>E?-1:0<E?1:0}var y;0===(y=q(f.getFullYear()-n.getFullYear()))&&0===(y=q(f.getMonth()-n.getMonth()))&&(y=q(f.getDate()-n.getDate()));return y}function v(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function r(f){var n=f.M;for(f=new Date((new Date(f.N+1900,0,1)).getTime());0<n;){var q=f.getMonth(),y=(Mb(f.getFullYear())?Nb:Ob)[q];if(n>y-f.getDate())n-=y-f.getDate()+1,f.setDate(1),11>q?f.setMonth(q+1):(f.setMonth(0),f.setFullYear(f.getFullYear()+1));else{f.setDate(f.getDate()+n);break}}q=new Date(f.getFullYear()+1,0,4);n=v(new Date(f.getFullYear(),0,
4));q=v(q);return 0>=l(n,f)?0>=l(q,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var p=I[d+40>>2];d={Ca:I[d>>2],Ba:I[d+4>>2],V:I[d+8>>2],ea:I[d+12>>2],W:I[d+16>>2],N:I[d+20>>2],H:I[d+24>>2],M:I[d+28>>2],Ma:I[d+32>>2],Aa:I[d+36>>2],Da:p?t(p):""};c=t(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var m in p)c=c.replace(new RegExp(m,"g"),p[m]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),x="January February March April May June July August September October November December".split(" ");p={"%a":function(f){return u[f.H].substring(0,3)},"%A":function(f){return u[f.H]},"%b":function(f){return x[f.W].substring(0,3)},"%B":function(f){return x[f.W]},
"%C":function(f){return h((f.N+1900)/100|0,2)},"%d":function(f){return h(f.ea,2)},"%e":function(f){return e(f.ea,2," ")},"%g":function(f){return r(f).toString().substring(2)},"%G":function(f){return r(f)},"%H":function(f){return h(f.V,2)},"%I":function(f){f=f.V;0==f?f=12:12<f&&(f-=12);return h(f,2)},"%j":function(f){for(var n=0,q=0;q<=f.W-1;n+=(Mb(f.N+1900)?Nb:Ob)[q++]);return h(f.ea+n,3)},"%m":function(f){return h(f.W+1,2)},"%M":function(f){return h(f.Ba,2)},"%n":function(){return"\n"},"%p":function(f){return 0<=
f.V&&12>f.V?"AM":"PM"},"%S":function(f){return h(f.Ca,2)},"%t":function(){return"\t"},"%u":function(f){return f.H||7},"%U":function(f){return h(Math.floor((f.M+7-f.H)/7),2)},"%V":function(f){var n=Math.floor((f.M+7-(f.H+6)%7)/7);2>=(f.H+371-f.M-2)%7&&n++;if(n)53==n&&(q=(f.H+371-f.M)%7,4==q||3==q&&Mb(f.N)||(n=1));else{n=52;var q=(f.H+7-f.M-1)%7;(4==q||5==q&&Mb(f.N%400-1))&&n++}return h(n,2)},"%w":function(f){return f.H},"%W":function(f){return h(Math.floor((f.M+7-(f.H+6)%7)/7),2)},"%y":function(f){return(f.N+
1900).toString().substring(2)},"%Y":function(f){return f.N+1900},"%z":function(f){f=f.Aa;var n=0<=f;f=Math.abs(f)/60;return(n?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.Da},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(m in p)c.includes(m)&&(c=c.replace(new RegExp(m,"g"),p[m](d)));c=c.replace(/\0\0/g,"%");m=Ta(c,!1);if(m.length>b)return 0;w.set(m,a);return m.length-1}
function gb(a,b,c,d){a||(a=this);this.parent=a;this.I=a.I;this.R=null;this.id=bb++;this.name=b;this.mode=c;this.B={};this.C={};this.rdev=d}Object.defineProperties(gb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},wa:{get:function(){return 16384===(this.mode&61440)}},va:{get:function(){return 8192===(this.mode&61440)}}});xb();R=Array(4096);
nb(O,"/");V("/tmp",16895,0);V("/home",16895,0);V("/home/web_user",16895,0);(()=>{V("/dev",16895,0);Ra(259,{read:()=>0,write:(b,c,d,e)=>e});ob("/dev/null",259);Qa(1280,Ua);Qa(1536,Va);ob("/dev/tty",1280);ob("/dev/tty1",1536);var a=Na();W("/dev","random",a);W("/dev","urandom",a);V("/dev/shm",16895,0);V("/dev/shm/tmp",16895,0)})();
(()=>{V("/proc",16895,0);var a=V("/proc/self",16895,0);V("/proc/self/fd",16895,0);nb({I:()=>{var b=Xa(a,"fd",16895,73);b.B={lookup:(c,d)=>{var e=Q[+d];if(!e)throw new N(8);c={parent:null,I:{oa:"fake"},B:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();var Fb;g.FS_createPath=Ab;g.FS_createDataFile=Cb;g.FS_createPreloadedFile=Gb;g.FS_unlink=qb;g.FS_createLazyFile=Eb;g.FS_createDevice=W;
function Ta(a,b){for(var c=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++c:c=2047>=e?c+2:65535>=e?c+3:c+4}c=Array(c+1);a=qa(a,c,0,c.length);b&&(c.length=a);return c}
var Rb={g:function(a,b,c){Hb=c;try{var d=Z(a);switch(b){case 0:var e=Y();return 0>e?-28:mb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Y(),d.flags|=e,0;case 5:return e=Y(),sa[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return I[Qb()>>2]=28,-1;default:return-28}}catch(h){if("undefined"==typeof X||!(h instanceof N))throw h;return-h.J}},i:function(a,b,c){Hb=c;try{var d=Z(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?
0:-59;case 21519:if(!d.tty)return-59;var e=Y();return I[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=Y();if(!d.C.ua)throw new N(59);return d.C.ua(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:H("bad ioctl syscall "+b)}}catch(h){if("undefined"==typeof X||!(h instanceof N))throw h;return-h.J}},f:function(a,b,c,d){Hb=d;try{b=t(b);var e=b;if("/"===e.charAt(0))b=e;else{if(-100===a)var h="/";else{var l=Q[a];if(!l)throw new N(8);h=l.path}if(0==e.length)throw new N(44);
b=M(h+"/"+e)}var v=d?Y():0;return tb(b,c,v).fd}catch(r){if("undefined"==typeof X||!(r instanceof N))throw r;return-r.J}},p:function(){return Date.now()},k:function(){return!0},a:function(){H("")},n:function(){return 2147483648},j:Ib,b:function(a){var b=pa.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);e=e.min.call(e,2147483648,d+(65536-d%65536)%65536);a:{try{la.grow(e-ra.byteLength+65535>>>16);ta();var h=1;break a}catch(l){}h=
void 0}if(h)return!0}return!1},o:function(a,b){var c=0;Kb().forEach(function(d,e){var h=b+c;e=k[a+4*e>>2]=h;for(h=0;h<d.length;++h)w[e++>>0]=d.charCodeAt(h);w[e>>0]=0;c+=d.length+1});return 0},h:function(a,b){var c=Kb();k[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});k[b>>2]=d;return 0},c:function(a){try{var b=Z(a);ub(b);return 0}catch(c){if("undefined"==typeof X||!(c instanceof N))throw c;return c.J}},e:function(a,b,c,d){try{a:{var e=Z(a);a=b;for(var h=b=0;h<c;h++){var l=k[a>>2],v=
k[a+4>>2];a+=8;var r=e,p=l,m=v,u=void 0,x=w;if(0>m||0>u)throw new N(28);if(null===r.fd)throw new N(8);if(1===(r.flags&2097155))throw new N(8);if(16384===(r.node.mode&61440))throw new N(31);if(!r.C.read)throw new N(28);var f="undefined"!=typeof u;if(!f)u=r.position;else if(!r.seekable)throw new N(70);var n=r.C.read(r,x,p,m,u);f||(r.position+=n);var q=n;if(0>q){var y=-1;break a}b+=q;if(q<v)break}y=b}I[d>>2]=y;return 0}catch(E){if("undefined"==typeof X||!(E instanceof N))throw E;return E.J}},l:function(a,
b,c,d,e){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var h=Z(a);vb(h,b,d);Ia=[h.position>>>0,(L=h.position,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];I[e>>2]=Ia[0];I[e+4>>2]=Ia[1];h.Z&&0===b&&0===d&&(h.Z=null);return 0}catch(l){if("undefined"==typeof X||!(l instanceof N))throw l;return l.J}},d:function(a,b,c,d){try{a:{var e=Z(a);a=b;for(var h=b=0;h<c;h++){var l=k[a>>2],v=k[a+4>>2];a+=
8;var r=wb(e,w,l,v);if(0>r){var p=-1;break a}b+=r}p=b}k[d>>2]=p;return 0}catch(m){if("undefined"==typeof X||!(m instanceof N))throw m;return m.J}},m:function(a,b,c,d){return Pb(a,b,c,d)}};
(function(){function a(e){g.asm=e.exports;la=g.asm.q;ta();ua=g.asm.u;wa.unshift(g.asm.r);Ca("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Ha().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(e,function(h){G("failed to asynchronously prepare wasm: "+h);H(h)})}var d={a:Rb};Ba("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return G("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ka||
"function"!=typeof WebAssembly.instantiateStreaming||Ea()||K.startsWith("file://")||A||"function"!=typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(h){G("wasm streaming compile failed: "+h);G("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.r).apply(null,arguments)};
g._allocateBuffer=function(){return(g._allocateBuffer=g.asm.s).apply(null,arguments)};g._detectCode=function(){return(g._detectCode=g.asm.t).apply(null,arguments)};
var Qb=g.___errno_location=function(){return(Qb=g.___errno_location=g.asm.v).apply(null,arguments)},Da=g.___trap=function(){return(Da=g.___trap=g.asm.w).apply(null,arguments)},Sb=g.stackSave=function(){return(Sb=g.stackSave=g.asm.x).apply(null,arguments)},Tb=g.stackRestore=function(){return(Tb=g.stackRestore=g.asm.y).apply(null,arguments)},Vb=g.stackAlloc=function(){return(Vb=g.stackAlloc=g.asm.z).apply(null,arguments)};g.___emscripten_embedded_file_data=1369280;
g.ccall=function(a,b,c,d){var e={string:function(p){var m=0;if(null!==p&&void 0!==p&&0!==p){var u=(p.length<<2)+1;m=Vb(u);qa(p,pa,m,u)}return m},array:function(p){var m=Vb(p.length);w.set(p,m);return m}};a=g["_"+a];var h=[],l=0;if(d)for(var v=0;v<d.length;v++){var r=e[c[v]];r?(0===l&&(l=Sb()),h[v]=r(d[v])):h[v]=d[v]}c=a.apply(null,h);return c=function(p){0!==l&&Tb(l);return"string"===b?t(p):"boolean"===b?!!p:p}(c)};g.addRunDependency=Ba;g.removeRunDependency=Ca;g.FS_createPath=Ab;
g.FS_createDataFile=Cb;g.FS_createPreloadedFile=Gb;g.FS_createLazyFile=Eb;g.FS_createDevice=W;g.FS_unlink=qb;var Wb;Aa=function Xb(){Wb||Yb();Wb||(Aa=Xb)};
function Yb(){function a(){if(!Wb&&(Wb=!0,g.calledRun=!0,!ma)){g.noFSInit||yb||(yb=!0,xb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?W("/dev","stdin",g.stdin):pb("/dev/tty","/dev/stdin"),g.stdout?W("/dev","stdout",null,g.stdout):pb("/dev/tty","/dev/stdout"),g.stderr?W("/dev","stderr",null,g.stderr):pb("/dev/tty1","/dev/stderr"),tb("/dev/stdin",0),tb("/dev/stdout",1),tb("/dev/stderr",1));cb=!1;Ja(wa);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();xa.unshift(b)}Ja(xa)}}if(!(0<J)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ya();Ja(va);0<J||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=Yb;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Yb();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
